config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :courses, except: [:edit, :update] do
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]

      put :sort

      member do
        delete :delete_media
      end
    end

    resources :enrollments, only: [:new, :create] do
      get :checkout_success, on: :collection
    end

    resources :course_wizard, controller: 'courses/course_wizard'

    get :my_enrolled, :pending_review, :my_created, :pending_approval, on: :collection

    member do
      get :analytics
      patch :approve
      patch :reject
    end
  end

  resources :enrollments do
    get :students, on: :collection
    get :certificate, on: :member
  end

  get 'activities', to: 'home#activities'
  get 'analytics', to: 'home#analytics'

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'courses_popularity'
    get 'money_makers'
  end

  resources :tags, only: [:index, :create, :destroy]

  get 'privacy_policy', to: 'static_pages#privacy_policy'

  # Prevent Chrome DevTools Routing Errors
  get '/.well-known/appspecific/com.chrome.devtools.json', to: proc { [200, { 'Content-Type' => 'application/json' }, ['{}']] }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @enrolled_courses = Course.enrolled_by(current_user).most_recent_enrolled.limit(3) if current_user
    @popular_courses = Course.published.approved.popular.most_recent.limit(3)
    @top_rated_courses = Course.published.approved.top_rated.most_recent.limit(3)
    @most_recent_courses = Course.published.approved.most_recent.limit(3)
    @reviewed_enrollments = Enrollment.reviewed.top_rated.recently_updated.limit(3)
    @popular_tags = Tag.in_use.most_popular.limit(10)
  end

  def activities
    if current_user.has_role?(:admin)
      @pagy, @activities = pagy(PublicActivity::Activity.all.order(created_at: :desc), items: 20)
    else
      redirect_to root_path, alert: unauthorized_msg
    end
  end

  def analytics
    redirect_to root_path, alert: unauthorized_msg unless current_user.has_role?(:admin)
  end

  private

  def unauthorized_msg
    'You are not authorized to perform this action.'
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/activities.html.erb
<% content_for :title do %>
  Activities
<% end %>
<h3>
  <div class="text-center">
    Activities
    <span class="badge bg-info"><%= @activities.count %></span>
  </div>
</h3>
<p></p>
<ul class="list-group">
  <% @activities.each do |activity| %>
    <li class="list-group-item">
      <%= activity.created_at.strftime('%Y-%m-%d %H:%m') %>
      <%= "(#{time_ago_in_words(activity.created_at)})" %>
      <%= type_tag(activity.trackable_type) %>
      <%= activity.trackable_type %>
      <% if activity.trackable %>
        <%= link_to activity.trackable, activity_path(activity) %>
      <% else %>
        <i>[Deleted]</i>
      <% end %>
      <%= action_tag(activity.key.split('.').last) %>
      <%= activity.key %>
      <% if activity.owner %>
        by
        <%= link_to activity.owner, user_path(activity.owner) %>
      <% end %>
      <% if activity.parameters.any? %>
        <%= "with #{activity.parameters}" %>
      <% end %>
    </li>
  <% end %>
</ul>
<div class="mt-3">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/home/analytics.html.erb
<h4 class="text-center mt-5">New users per day</h3>
<%= line_chart charts_users_per_day_path %>
<h4 class="text-center mt-5">New enrollments per day</h3>
<%= column_chart charts_enrollments_per_day_path %>
<h4 class="text-center mt-5">Most enrolled courses</h3>
<%= bar_chart charts_courses_popularity_path %>
<h4 class="text-center mt-5">Money makers</h3>
<%= bar_chart charts_money_makers_path %>

app/views/home/index.html.erb
<% content_for :title do %>
  Learn anything, on your schedule
<% end %>
<div class="container-fluid text-lg-left p-5 bg-light">
  <div class="display-5 fw-bold mb-4">
    What do you want to learn today?
  </div>
  <% if current_user %>
    <%= search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f| %>
      <div class="d-flex">
        <%= f.search_field :title_or_short_description_cont, class: "form-control me-2", placeholder: "Find a course", aria_label: 'Search', autocomplete: 'off' %>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </div>
    <% end %>
  <% else %>
    <div class="display-6 mb-3">
      Join to access all courses
    </div>
    <%= link_to new_user_session_path, class: 'btn btn-outline-secondary' do %>
      Log in
      <i class="fa-solid fa-arrow-right-to-bracket"></i>
    <% end %>
    <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-outline-secondary' %>
    <h5 class="fw-light mt-4">Or continue with:</h5>
    <%= link_to user_google_oauth2_omniauth_authorize_path, class: 'btn btn-danger btn-lg text-light', method: :post do %>
      Google
      <i class="fa-brands fa-google"></i>
    <% end %>
    <%= link_to user_github_omniauth_authorize_path, class: 'btn btn-dark btn-lg text-light', method: :post do %>
      Github
      <i class="fa-brands fa-github"></i>
    <% end %>
    <%= link_to user_facebook_omniauth_authorize_path, class: 'btn btn-primary btn-lg text-light', method: :post do %>
      Facebook
      <i class="fa-brands fa-facebook"></i>
    <% end %>
  <% end %>
</div>
<div class="card-group mt-3 mb-4">
  <div class="card card-body">
    <h1>
      <i class="fa-solid fa-graduation-cap"></i>
    </h1>
    <%= Course.count %>
    online courses
    <div class="row"></div>
    Explore a variety of fresh topics
  </div>
  <div class="card card-body">
    <h1>
      <i class="fa-solid fa-chalkboard-user"></i>
    </h1>
    <%= Course.distinct.count(:user_id) %>
    expert instructors
    <div class="row"></div>
    Find the right instructor for you
  </div>
  <div class="card card-body">
    <h1>
      <i class="fa-solid fa-user-graduate"></i>
    </h1>
    <%= User.count %>
    active learners
    <div class="row"></div>
    Join the knowledge-sharing community
  </div>
  <div class="card card-body">
    <h1>
      <i class="fa-solid fa-infinity"></i>
    </h1>
    Lifetime access
    <div class="row"></div>
    Learn on your schedule
  </div>
</div>
<% if current_user %>
  <div class="row my-3">
    <h3>
      <i class="fa-solid fa-rocket"></i>
      Continue Learning
    </h3>
    <div class="container">
      <div class="row" data-masonry='{"percentPosition": true }'>
        <% @enrolled_courses.each do |course| %>
          <div class="col-sm-6 col-lg-4 mb-2">
            <%= render "courses/course", course: course %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="text-end">
      <%= link_to my_enrolled_courses_path do %>
        My enrolled courses
        <i class="fa-solid fa-up-right-from-square"></i>
      <% end %>
    </div>
  </div>
<% end %>
<div class="row my-3">
  <h3>
    <i class="fa-solid fa-chart-line"></i>
    Popular Courses
  </h3>
  <div class="container">
    <div class="row" data-masonry='{"percentPosition": true }'>
      <% @popular_courses.each do |course| %>
        <div class="col-sm-6 col-lg-4 mb-2">
          <%= render "courses/course", course: course %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="text-end">
    <%= link_to courses_path(courses_search: {s: 'enrollments_count desc'}) do %>
      Most popular courses
      <i class="fa-solid fa-up-right-from-square"></i>
    <% end %>
  </div>
</div>
<div class="row my-3">
  <h3>
    <i class="fa-solid fa-star"></i>
    Top Rated Courses
  </h3>
  <div class="container">
    <div class="row" data-masonry='{"percentPosition": true }'>
      <% @top_rated_courses.each do |course| %>
        <div class="col-sm-6 col-lg-4 mb-2">
          <%= render "courses/course", course: course %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="text-end">
    <%= link_to courses_path(courses_search: {s: 'average_rating desc'}) do %>
      Top rated courses
      <i class="fa-solid fa-up-right-from-square"></i>
    <% end %>
  </div>
</div>
<div class="row my-3">
  <h3>
    <i class="fa-solid fa-clock"></i>
    Most Recent Courses
  </h3>
  <div class="container">
    <div class="row" data-masonry='{"percentPosition": true }'>
      <% @most_recent_courses.each do |course| %>
        <div class="col-sm-6 col-lg-4 mb-2">
          <%= render "courses/course", course: course %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="text-end">
    <%= link_to courses_path(courses_search: {s: 'created_at desc'}) do %>
      Latest courses
      <i class="fa-solid fa-up-right-from-square"></i>
    <% end %>
  </div>
</div>
<div class="row mt-3 mb-5">
  <h3>
    <i class="fa-solid fa-tags"></i>
    Most popular tags
  </h3>
  <div class="container mt-2">
    <% @popular_tags.each do |tag| %>
      <%= link_to courses_path(courses_search: {course_tags_tag_id_eq: tag.id}), class: "btn btn-info text-light tag-btn" do %>
        <h5 class="my-1">
          <%= tag.name %>
          <%= tag.course_tags_count %>
        </h5>
      <% end %>
    <% end %>
  </div>
</div>
<div class="row my-3">
  <h3>
    <i class="fa-solid fa-comments"></i>
    What our students have to say
  </h3>
  <div class="container">
    <div class="row" data-masonry='{"percentPosition": true }'>
      <% @reviewed_enrollments.each do |enrollment| %>
        <div class="col-sm-6 col-lg-4 mb-2">
          <%= render "enrollments/enrollment", enrollment: enrollment %>
        </div>
      <% end %>
    </div>
  </div>
</div>