config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :courses, except: [:edit, :update] do
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]

      put :sort

      member do
        delete :delete_media
      end
    end

    resources :enrollments, only: [:new, :create] do
      get :checkout_success, on: :collection
    end

    resources :course_wizard, controller: 'courses/course_wizard'

    get :my_enrolled, :pending_review, :my_created, :pending_approval, on: :collection

    member do
      get :analytics
      patch :approve
      patch :reject
    end
  end

  resources :enrollments do
    get :students, on: :collection
    get :certificate, on: :member
  end

  get 'activities', to: 'home#activities'
  get 'analytics', to: 'home#analytics'

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'courses_popularity'
    get 'money_makers'
  end

  resources :tags, only: [:index, :create, :destroy]

  get 'privacy_policy', to: 'static_pages#privacy_policy'

  # Prevent Chrome DevTools Routing Errors
  get '/.well-known/appspecific/com.chrome.devtools.json', to: proc { [200, { 'Content-Type' => 'application/json' }, ['{}']] }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :course, counter_cache: true
  belongs_to :user, counter_cache: true

  validates :user, :course, presence: true

  validates_presence_of :rating, if: :review?
  validates_presence_of :review, if: :rating?

  validates_uniqueness_of :user_id, scope: :course_id
  validates_uniqueness_of :course_id, scope: :user_id

  validate :user_cannot_be_course_owner

  extend FriendlyId
  friendly_id :to_s, use: :slugged

  include PublicActivity::Model
  tracked owner: ->(controller, _model) { controller.current_user }

  scope :pending_review, -> { where(rating: [0, nil], review: ['', nil]) }
  scope :rated, -> { where.not(rating: [0, nil]) }
  scope :reviewed, -> { where.not(review: ['', nil]) }
  scope :top_rated, -> { order(rating: :desc) }
  scope :recently_updated, -> { order(updated_at: :desc) }

  def to_s
    course.to_s
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[review rating created_at updated_at]
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[user course]
  end

  after_save do
    course.update_average_rating unless rating.nil? || rating.zero?
  end

  after_destroy do
    course.update_average_rating
    course.calculate_income
    user.calculate_balance
  end

  after_create do
    course.calculate_income
    user.calculate_balance
  end

  protected

  def user_cannot_be_course_owner
    return unless new_record? && user_id == course.user_id

    errors.add(:base, 'You can not enroll to your own course')
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:certificate]

  before_action :set_enrollment, only: %i[show edit update destroy certificate]
  before_action :set_course, only: %i[new create checkout_success]

  # GET /enrollments or /enrollments.json
  def index
    @ransack_path = enrollments_path
    @q = Enrollment.ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user, :course))
    authorize @enrollments
  end

  def students
    @ransack_path = students_enrollments_path
    @q = Enrollment.joins(:course).where(courses: { user_id: current_user.id }).ransack(params[:q])
    @pagy, @enrollments = pagy(@q.result.includes(:user))
    render :index
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  def certificate
    authorize @enrollment, :certificate?
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@enrollment.course.title}, #{@enrollment.user.email}",
               page_size: 'A4',
               template: 'enrollments/certificate.pdf.erb'
      end
    end
  end

  # GET /enrollments/new
  def new
    if current_user && @course.already_enrolled?(current_user)
      redirect_to course_path(@course), notice: 'You have already enrolled in the course.'
    else
      @enrollment = Enrollment.new
    end
  end

  # GET /enrollments/1/edit
  def edit
    authorize @enrollment
  end

  # POST /enrollments or /enrollments.json
  def create
    if @course.price.positive?
      session = create_checkout_session(@course)
      redirect_to session.url, status: :see_other
    else
      checkout_success
    end
  end

  def checkout_success
    @enrollment = @current_user.enroll_in(@course)
    dispatch_mailers(@enrollment)
    redirect_to course_path(@course), notice: 'You have successfully enrolled in the course.'
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    authorize @enrollment
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to @enrollment, notice: 'Enrollment was successfully updated.' }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    authorize @enrollment
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_path, status: :see_other, notice: 'Enrollment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_enrollment
    @enrollment = Enrollment.friendly.find(params[:id])
  end

  def set_course
    @course = Course.friendly.find(params[:course_id])
  end

  def create_checkout_session(course)
    Stripe::Checkout::Session.create(
      {
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
          quantity: 1,
          price_data: {
            product_data: { name: "Enrollment for #{course.title}" },
            unit_amount: course.price,
            currency: 'usd'
          }
        }],
        mode: 'payment',
        success_url: checkout_success_course_enrollments_url(course),
        cancel_url: new_course_enrollment_url(course)
      }
    )
  end

  def dispatch_mailers(enrollment)
    EnrollmentMailer.new_enrollment(enrollment).deliver_later
    EnrollmentMailer.new_student(enrollment).deliver_later
  end

  # Only allow a list of trusted parameters through.
  def enrollment_params
    params.require(:enrollment).permit(:rating, :review)
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.erb
<div class="card">
  <div class="card-header">
    <% if current_user %>
      <i class="fa-solid fa-user"></i>
      <%= link_to enrollment.user, user_path(enrollment.user) %>
    <% end %>
    <i class="fa-solid fa-graduation-cap"></i>
    <%= link_to enrollment.course, course_path(enrollment.course) %>
    <i class="fa-solid fa-clock"></i>
    <%= time_ago_in_words(enrollment.created_at) %>
  </div>
  <div class="card-body">
    <i class="text-warning fa-solid fa-star"></i>
    <b>
      <%= enrollment.rating %>
    </b>
    <i class="fa-solid fa-comment"></i>
    <small>
      <%= enrollment.review %>
    </small>
  </div>
  <% if current_user %>
    <div class="card-footer">
      <%= link_to 'Edit review', edit_enrollment_path(enrollment) if policy(enrollment).edit? %>
    </div>
  <% end %>
</div>

app/views/enrollments/_form.html.erb
<%= simple_form_for(@enrollment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :rating, as: :radio_buttons, collection: 1..5, item_wrapper_class: 'form-check form-check-inline' %>
    <%= f.input :review %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/enrollments/certificate.pdf.erb
<center>
  <div style="width: 1200px; height: 800px; padding: 20px; text-align: center; border: 10px solid #563d7c">
    <div style="width: 1150px; height: 750px; padding: 20px; text-align: center; border: 10px solid #563d7c">
      <br>
      <br>
      <br>
      <br>
      <span style="font-size: 50px; font-weight: bold">
        Certificate of completion
      </span>
      <p></p>
      <br>
      <br>
      <br>
      <br>
      <h3>This is to certify that the owner of the email address</h3>
      <u><%= @enrollment.user.email %></u>
      <h3>has successfully completed the course</h3>
      <u><%= @enrollment.course.title %></u>
      <h3>on the Paranabuka Courses platform</h3>
      <p></p>
      <br>
      <br>
      <br>
      <br>
      <b>Certificate ID:</b> <%= @enrollment.slug %>
      <p></p>
      <b>Certificate URL:</b> <%= request.base_url + request.original_fullpath %>
      <br>
      <br>
      <br>
      <center>
        <h3>
          <%= image_tag wicked_pdf_asset_base64('logo.png'), height: 30, width: 'auto' %>
          <p></p>
          www.courses.paranabuka.com
        </h3>
      </center>
    </div>
  </div>
</center>

app/views/enrollments/edit.html.erb
<% content_for :title do %>
  Review
  <%= @enrollment %>
<% end %>
<div class="card">
  <div class="card-header">
    <h3>
      <i class="text-warning fa-solid fa-star"></i>
      Add review
    </h3>
  </div>
  <div class="card-body">
    <%= render 'form', enrollment: @enrollment %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', course_path(@enrollment.course) %>
  </div>
</div>

app/views/enrollments/index.html.erb
<% content_for :title do %>
  <%= action_name.humanize %>
  enrollments
<% end %>
<h3>
  <div class="text-center">
    <%= action_name.humanize %>
    enrollments
    <span class="badge bg-info"><%= @enrollments.count %></span>
  </div>
</h3>
<div class="d-grid gap-3 mt-4">
  <div class="col-8">
    <%= search_form_for @q, url: @ransack_path do |f| %>
      <div class="input-group gap-2">
        <%= f.search_field :user_email_cont, placeholder: "User", class: "form-control form-control-sm", autocomplete: 'off' %>
        <%= f.search_field :course_title_cont, placeholder: "Course", class: "form-control form-control-sm", autocomplete: 'off' %>
        <%= f.search_field :rating_eq, placeholder: "Rating", class: "form-control form-control-sm", autocomplete: 'off' %>
        <%= f.search_field :review_cont, placeholder: "Review", class: "form-control form-control-sm", autocomplete: 'off' %>
        <span class="input-group-append">
          <button class="btn btn-primary btn-sm" type="submit">
            <span class="fa fa-search", aria-hidden="true"></span>
          </button>
        </span>
        <%= link_to @ransack_path, class: "btn btn-sm" do %>
          <i class="fa-solid fa-rotate"></i>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="table-responsive">
    <table class="table table-bordered table-striped table-sm">
      <thead>
        <tr>
          <th>ID</th>
          <th>
            <i class="fa-solid fa-user"></i>
            <%= sort_link(@q, :user_email, 'User') %>
          </th>
          <th>
            <i class="fa-solid fa-graduation-cap"></i>
            <%= sort_link(@q, :course_title, 'Course') %>
          </th>
          <th>
            <i class="fa-solid fa-lock-open"></i>
            <%= sort_link(@q, :created_at, 'Enrolled on') %>
          </th>
          <th>
            <i class="fa-solid fa-dollar-sign"></i>
            <%= sort_link(@q, :price, 'Price') %>
          </th>
          <th>
            <i class="fa-solid fa-spinner"></i>
            Progress
          </th>
          <th>
            <i class="fa-solid fa-certificate"></i>
            Certificate
          </th>
          <th>
            <i class="text-warning fa-solid fa-star"></i>
            <%= sort_link(@q, :rating, 'Rating') %>
          </th>
          <th>
            <i class="text-warning fa-solid fa-comment"></i>
            Review
          </th>
          <th>
            <i class="text-warning fa-solid fa-clock"></i>
            <%= sort_link(@q, :updated_at, 'Reviewed on') %>
          </th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @enrollments.each do |enrollment| %>
          <tr>
            <td><%= enrollment.id %></td>
            <td><%= link_to enrollment.user.username, user_path(enrollment.user) %></td>
            <td><%= link_to enrollment.course, course_path(enrollment.course) %></td>
            <td><%= enrollment.created_at.strftime("%Y-%m-%d %H:%M") %></td>
            <td><%= number_to_currency(enrollment.price) %></td>
            <td><%= number_to_percentage(enrollment.course.progress(enrollment.user), precision: 0) %></td>
            <td><%= link_to 'Certificate', certificate_enrollment_path(enrollment, format: :pdf), target: :_blank, rel: :noopener if policy(enrollment).certificate? %></td>
            <td><%= enrollment.rating %></td>
            <td><%= enrollment.review %></td>
            <td><%= enrollment.updated_at.strftime("%Y-%m-%d %H:%M") if enrollment.rating.present? %></td>
            <td><%= link_to 'See review', enrollment %></td>
            <td><%= link_to 'Add review', edit_enrollment_path(enrollment) if policy(enrollment).edit? %></td>
            <td><%= link_to 'Delete enrollment', enrollment, method: :delete, data: { confirm: 'Are you sure?' } if policy(enrollment).destroy? %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/enrollments/new.html.erb
<% content_for :title do %>
  New Enrollment
<% end %>
<div class="card">
  <div class="card-header">
    <h3>
      <i class="fa-solid fa-graduation-cap"></i>
      <%= link_to @course.title, @course %>
      <hr>
      <i class="fa-solid fa-lock-open"></i>
      Enroll in
    </h3>
  </div>
  <div class="card-body">
    <%= form_tag course_enrollments_path(@course) do %>
      <% if @course.price.positive? %>
        <%= submit_tag "Pay #{number_to_currency@course.price / 100.0}", class: 'btn btn-success btn-lg' %>
      <% else %>
        <%= submit_tag 'Enroll for free', class: 'btn btn-success btn-lg' %>
      <% end %>
    <% end %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', enrollments_path %>
  </div>
</div>

app/views/enrollments/show.html.erb
<%= render partial: "enrollment", locals: { enrollment: @enrollment } %>