config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :courses, except: [:edit, :update] do
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]

      put :sort

      member do
        delete :delete_media
      end
    end

    resources :enrollments, only: [:new, :create] do
      get :checkout_success, on: :collection
    end

    resources :course_wizard, controller: 'courses/course_wizard'

    get :my_enrolled, :pending_review, :my_created, :pending_approval, on: :collection

    member do
      get :analytics
      patch :approve
      patch :reject
    end
  end

  resources :enrollments do
    get :students, on: :collection
    get :certificate, on: :member
  end

  get 'activities', to: 'home#activities'
  get 'analytics', to: 'home#analytics'

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'courses_popularity'
    get 'money_makers'
  end

  resources :tags, only: [:index, :create, :destroy]

  get 'privacy_policy', to: 'static_pages#privacy_policy'

  # Prevent Chrome DevTools Routing Errors
  get '/.well-known/appspecific/com.chrome.devtools.json', to: proc { [200, { 'Content-Type' => 'application/json' }, ['{}']] }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course, counter_cache: true

  has_many :user_lessons, dependent: :destroy
  has_many :comments, dependent: :nullify

  has_rich_text :content
  has_one_attached :video
  has_one_attached :video_thumbnail

  validates :title, presence: true, length: { maximum: 60 }
  validates_uniqueness_of :title, scope: :course_id
  validates :content, :course, presence: true
  validates :video,
            content_type: ['video/mp4'],
            size: { less_than: 100.megabytes }
  validates :video_thumbnail,
            content_type: ['image/png', 'image/jpeg'],
            size: { less_than: 200.kilobytes }

  extend FriendlyId
  friendly_id :title, use: :slugged

  include PublicActivity::Model
  tracked owner: ->(controller, _model) { controller.current_user }

  include RankedModel
  ranks :row_order, with_same: :course_id

  def to_s
    title
  end

  def completed_by?(user)
    user_lessons.where(user: user).exists?
  end

  def previous
    course.lessons.where('row_order < ?', row_order).order(row_order: :desc).limit(1).first
  end

  def next
    course.lessons.where('row_order > ?', row_order).order(row_order: :asc).limit(1).first
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_course, only: %i[new create show edit update destroy delete_media]
  before_action :set_lesson, only: %i[show edit update destroy delete_media]

  # GET /lessons or /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1 or /lessons/1.json
  def show
    authorize @lesson
    current_user.view_lesson(@lesson)
    @lessons = @course.lessons.rank(:row_order)
    @previous_lesson = @lesson.previous
    @next_lesson = @lesson.next
    @comment = Comment.new
    @comments = @lesson.comments.order(created_at: :desc)
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
    authorize @lesson
  end

  # POST /lessons or /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    @lesson.course_id = @course.id
    authorize @lesson

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1 or /lessons/1.json
  def update
    authorize @lesson
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1 or /lessons/1.json
  def destroy
    authorize @lesson
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to course_path(@course), status: :see_other, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sort
    @course = Course.friendly.find(params[:course_id])
    lesson = Lesson.friendly.find(params[:lesson_id])
    authorize lesson, :update?
    lesson.update(lesson_params)
    render body: nil
  end

  def delete_media
    authorize @lesson, :edit?
    @lesson.video.purge
    @lesson.video_thumbnail.purge
    redirect_to edit_course_lesson_path(@course, @lesson), notice: 'Media was sucessfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.friendly.find(params[:course_id])
  end

  def set_lesson
    @lesson = Lesson.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def lesson_params
    params.require(:lesson).permit(:title, :content, :video, :video_thumbnail, :row_order_position)
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= simple_form_for([@course, @lesson]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="d-grid gap-2">
    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :content, as: :rich_text_area %>
      <%= f.input :video %>
      <% if @lesson.video.attached? %>
        <h6 class="text-secondary">
          <i class="fa-solid fa-file-video"></i>
          <%= "#{@lesson.video.filename} (#{number_to_human_size(@lesson.video.byte_size)})" %>
        </h6>
      <% end %>
      <%= f.input :video_thumbnail %>
      <% if @lesson.video_thumbnail.attached? %>
        <figure>
          <%= image_tag @lesson.video_thumbnail, class: 'img-thumbnail', alt: 'Lesson video thumbnail', width: '300px' %>
          <figcaption class="figure-caption">
            <%= "#{@lesson.video_thumbnail.filename} (#{number_to_human_size(@course.cover.byte_size)})" %>
          </figcaption>
        </figure>
      <% end %>
      <% if @lesson.video.attached? || @lesson.video_thumbnail.attached? %>
        <%= link_to 'Remove media', delete_media_course_lesson_path(@course, @lesson), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<div class="card">
  <div class="card-header">
    <% if !@course.owned_by?(current_user) && lesson.completed_by?(current_user) %>
      <i class="text-success fa-solid fa-square-check"></i>
    <% else %>
      <i class="text-secondary fa-regular fa-square"></i>
    <% end %>
    <%= link_to lesson.title, course_lesson_path(@course, lesson) %>
  </div>
  <% if policy(lesson).show? %>
    <div class="card-body">
      <% if lesson.video.attached? %>
        <video controls preload="metadata" width="100%" poster="<%= url_for(lesson.video_thumbnail) if lesson.video_thumbnail.attached? %>">
          <source src="<%= rails_blob_url(lesson.video) %>" type="<%= lesson.video.content_type %>">
        </video>
      <% end %>
      <%= lesson.content %>
    </div>
    <% if policy(lesson).edit? %>
      <div class="card-footer">
        <%= link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-sm btn-warning' %>
        <%= link_to 'Destroy', [@course, lesson], class: 'btn btn-sm btn-danger text-light', method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
    <div class="card-footer">
      <div class="float-start">
        <%= link_to course_lesson_path(@course, @previous_lesson), class: 'btn btn-sm btn-outline-secondary fw-bold' do %>
          <i class="fa-solid fa-arrow-left"></i>
          Previous
        <% end if @previous_lesson.present? %>
      </div>
      <div class="float-end">
        <%= link_to course_lesson_path(@course, @next_lesson), class: 'btn btn-sm btn-outline-secondary fw-bold' do %>
          <i class="fa-solid fa-arrow-right"></i>
          Next
        <% end if @next_lesson.present? %>
      </div>
    </div>
  <% end %>
</div>

app/views/lessons/_lesson_preview.html.erb
<div class="d-flex align-items-center">
  <div class="me-auto">
    <% if current_user && !@course.owned_by?(current_user) && lesson.completed_by?(current_user) %>
      <i class="text-success fa-solid fa-square-check"></i>
    <% else %>
      <i class="text-secondary fa-regular fa-square"></i>
    <% end %>
    <%= link_to course_lesson_path(@course, lesson) do %>
      <%= "#{lesson.row_order_rank + 1}. #{lesson.title}" %>
    <% end %>
  </div>
  <div>
    <i class="fa-solid fa-message"></i>
    <%= lesson.comments_count %>
    <% if policy(lesson).edit? %>
      <i class="fa-solid fa-user-group"></i>
      <%= lesson.user_lessons_count %>
      <i class="fa-solid fa-eye"></i>
      <%= lesson.user_lessons.map(&:impressions).sum %>
      <%= link_to 'Edit', edit_course_lesson_path(@course, lesson), class: 'btn btn-warning btn-sm text-dark' %>
      <%= link_to 'Destroy', [@course, lesson], class: 'btn btn-danger btn-sm text-light', method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>

app/views/lessons/edit.html.erb
<% content_for :title do %>
  Edit
  <%= @lesson.title %>
<% end %>
<div class="card">
  <div class="card-header">
    <h3>
      <i class="fa-regular fa-square-check"></i>
      Editing Lesson
    </h3>
  </div>
  <div class="card-body">
    <%= render 'form', lesson: @lesson %>
  </div>
  <div class="card-footer">
    <%= link_to 'Show', course_lesson_path(@course, @lesson) %> |
    <%= link_to 'Back', course_path(@course) %>
  </div>
</div>

app/views/lessons/new.html.erb
<% content_for :title do %>
  New lesson
<% end %>
<div class="d-flex gap-2 mb-3">
  <%= link_to 'Courses', courses_path %> /
  <%= link_to course_path(@course) do %>
    <i class="fa-solid fa-graduation-cap"></i>
    <%= @course.title %>
  <% end %> /
  New lesson
</div>
<div>
  <div class="card">
    <div class="card-header">
      <h3>
        <i class="fa-regular fa-square-check"></i>
        New Lesson
      </h3>
    </div>
    <div class="card-body">
      <%= render 'form', lesson: @lesson %>
    </div>
    <div class="card-footer">
      <%= link_to 'Back', course_path(@course) %>
    </div>
  </div>
</div>

app/views/lessons/show.html.erb
<% content_for :title do %>
  <%= @lesson.title %>
<% end %>
<div class="d-flex gap-2 mb-3">
  <%= link_to 'Courses', courses_path %> /
  <%= link_to course_path(@course) do %>
    <i class="fa-solid fa-graduation-cap"></i>
    <%= @course.title %>
  <% end %> /
  <%= link_to course_lesson_path(@course, @lesson) do %>
    <i class="fa-solid fa-list-check"></i>
    <%= @lesson.title %>
  <% end %>
</div>
<div class="row">
  <div class="col-lg-8 mb-3">
    <%= render partial: "lesson", locals: { lesson: @lesson } %>
    <h4 class="mt-3">
      <i class="fa-solid fa-message"></i>
      Comments:
      <%= @lesson.comments_count %>
    </h4>
    <div class="card mb-3">
      <div class="card-header">New comment:</div>
      <div class="card-body">
        <%= render 'lessons/comments/form' %>
      </div>
    </div>
    <div class="d-grid gap-2">
      <% @comments.each do |comment| %>
        <%= render 'lessons/comments/comment', comment: comment %>
      <% end %>
    </div>
  </div>
  <div class="col-lg-4">
    <ul class="list-group">
      <li class="list-group-item list-group-item-dark fw-bold">
        <i class="fa-solid fa-graduation-cap"></i>
        <%= link_to @course.title, course_path(@course) %>
        <div class="float-end">
          <i class="fa-solid fa-spinner"></i>
          <%= number_to_percentage(@course.progress(current_user), precision: 0) %>
        </div>
      </li>
      <% @lessons.each do |lesson| %>
        <li class="list-group-item <%= 'list-group-item-primary fw-bold' if lesson == @lesson %>">
          <%= render partial: 'lessons/lesson_preview', locals: { lesson: lesson } %>
        </li>
      <% end %>
    </ul>
  </div>
</div>