config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :users, only: [:index, :show, :edit, :update]

  resources :courses, except: [:edit, :update] do
    resources :lessons, except: [:index] do
      resources :comments, except: [:index]

      put :sort

      member do
        delete :delete_media
      end
    end

    resources :enrollments, only: [:new, :create] do
      get :checkout_success, on: :collection
    end

    resources :course_wizard, controller: 'courses/course_wizard'

    get :my_enrolled, :pending_review, :my_created, :pending_approval, on: :collection

    member do
      get :analytics
      patch :approve
      patch :reject
    end
  end

  resources :enrollments do
    get :students, on: :collection
    get :certificate, on: :member
  end

  get 'activities', to: 'home#activities'
  get 'analytics', to: 'home#analytics'

  namespace :charts do
    get 'users_per_day'
    get 'enrollments_per_day'
    get 'courses_popularity'
    get 'money_makers'
  end

  resources :tags, only: [:index, :create, :destroy]

  get 'privacy_policy', to: 'static_pages#privacy_policy'

  # Prevent Chrome DevTools Routing Errors
  get '/.well-known/appspecific/com.chrome.devtools.json', to: proc { [200, { 'Content-Type' => 'application/json' }, ['{}']] }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/courses/course_wizard_controller.rb
class Courses::CourseWizardController < ApplicationController
  include Wicked::Wizard

  before_action :set_course, only: %i[show update finish_wizard_path]
  before_action :set_progress, only: %i[show update]

  steps :general_info, :details, :lessons, :publish

  def show
    authorize @course, :edit?
    preload_tags if step == :details

    render_wizard
  end

  def update
    authorize @course, :edit?
    preload_tags if step == :details
    @course.update(course_params) unless step == :lessons && params[:course].blank?

    render_wizard @course
  end

  def finish_wizard_path
    authorize @course, :edit?
    course_path(@course)
  end

  private

  def set_course
    @course = Course.friendly.find(params[:course_id])
  end

  def set_progress
    current_step = wizard_steps.index(step)

    @progress =
      if wizard_steps.any? && current_step.present?
        ((current_step + 1).to_d / wizard_steps.count) * 100
      else
        0
      end
  end

  def preload_tags
    @tags = Tag.all.in_use
  end

  def course_params
    params.require(:course).permit(
      :title, :description, :short_description, :cover,
      :language, :level, :price,
      :published,
      tag_ids: [],
      lessons_attributes: %i[id title content _destroy]
    )
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]

  before_action :set_course, only: %i[show destroy approve reject analytics]
  before_action :preload_tags, only: %i[index new my_enrolled pending_review my_created pending_approval]

  # GET /courses or /courses.json
  def index
    @ransack_path = courses_path
    ransack_and_pagy_courses(Course.published.approved)
  end

  def my_enrolled
    @ransack_path = my_enrolled_courses_path
    ransack_and_pagy_courses(
      Course.joins(:enrollments)
            .where(enrollments: { user_id: current_user.id })
    )
    render :index
  end

  def pending_review
    @ransack_path = pending_review_courses_path
    ransack_and_pagy_courses(
      Course.joins(:enrollments)
            .merge(Enrollment.pending_review.where(user_id: current_user.id))
    )
    render :index
  end

  def my_created
    @ransack_path = my_created_courses_path
    ransack_and_pagy_courses(Course.where(user_id: current_user.id))
    render :index
  end

  # GET /courses/1 or /courses/1.json
  def show
    authorize @course
    @lessons = @course.lessons.rank(:row_order)
    @recent_reviews = @course.enrollments.reviewed.top_rated.recently_updated.limit(3)
    @similar_courses = Course.where.not(id: @course.id).published.approved
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  def pending_approval
    @ransack_path = pending_approval_courses_path
    ransack_and_pagy_courses(Course.published.not_approved)
    render :index
  end

  def approve
    authorize @course
    @course.update_attribute(:approved, true)
    redirect_to @course, notice: 'Course approved successfully.'
  end

  def reject
    authorize @course, :approve?
    @course.update_attribute(:approved, false)
    redirect_to @course, notice: 'Course rejected successfully.'
  end

  def analytics
    authorize @course, :owner?
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    authorize @course
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_course_wizard_index_path(@course), notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        preload_tags
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    authorize @course
    if @course.destroy
      respond_to do |format|
        format.html { redirect_to courses_path, status: :see_other, notice: 'Course was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to @course, alert: 'Course can not be destroyed since it has student(s).'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.friendly.find(params[:id])
  end

  def preload_tags
    @tags = Tag.all.in_use
  end

  def ransack_and_pagy_courses(query)
    @ransack_courses = query.ransack(params[:courses_search], search_key: :courses_search)
    @pagy, @courses = pagy(@ransack_courses.result.includes(:user, :course_tags, :tags))
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:title, :description, :short_description, :language, :level, :price, :published,
                                   :cover, tag_ids: [])
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def enroll_in(course)
    return check_price(course) unless current_user
    return view_analytics(course) if course.owned_by?(current_user)
    return keep_learning(course) if course.already_enrolled?(current_user)
    return proceed_to_payment(course) if course.price.positive?

    free_enrollment(course)
  end

  def review(course)
    return unless current_user && course.already_enrolled?(current_user)

    enrollment = course.enrollments.find_by(user_id: current_user.id)

    return unless enrollment
    return add_review(enrollment) unless enrollment.rating.present?

    see_review(enrollment)
  end

  def certificate(course)
    return unless current_user

    enrollment = current_user.enrollments.find_by(course_id: course.id)

    return unless enrollment
    return unless policy(enrollment).certificate?

    view_certificate(enrollment)
  end

  private

  def check_price(course)
    link_to 'Check price', new_course_enrollment_path(course), class: 'btn btn-success btn-md text-light'
  end

  def view_analytics(course)
    link_to 'You created this course. See analytics', analytics_course_path(course)
  end

  def keep_learning(course)
    link_to course_path(course) do
      "#{spinner_icon} #{number_to_percentage(course.progress(current_user), precision: 0)}".html_safe
    end
  end

  def proceed_to_payment(course)
    link_to number_to_currency(course.price / 100.0), new_course_enrollment_path(course),
            class: 'btn btn-success text-light'
  end

  def free_enrollment(course)
    link_to 'Free', new_course_enrollment_path(course), class: 'btn btn-success text-light'
  end

  def add_review(enrollment)
    link_to edit_enrollment_path(enrollment) do
      "#{star_icon} Add review".html_safe
    end
  end

  def see_review(enrollment)
    link_to enrollment do
      "#{review_icon} Your review".html_safe
    end
  end

  def view_certificate(enrollment)
    link_to certificate_enrollment_path(enrollment, format: :pdf), class: 'btn btn-primary btn-sm text-light',
                                                                   target: :_blank, rel: :noopener do
      "Certificate #{certificate_icon}".html_safe
    end
  end

  def star_icon
    content_tag(:i, '', class: 'text-warning fa-solid fa-star')
  end

  # def rating_stars(rating)
  #   rating.times.map do
  #     star_icon
  #   end.join
  # end

  def review_icon
    content_tag(:i, '', class: 'fa-solid fa-comment')
  end

  def spinner_icon
    content_tag(:i, '', class: 'fa-solid fa-spinner')
  end

  def certificate_icon
    content_tag(:i, '', class: 'fa-solid fa-certificate')
  end
end

app/views/courses/_course.html.erb
<div class="card">
  <div class="card-header">
    <i class="fa-solid fa-graduation-cap"></i>
    <%= link_to course.title, course %>
  </div>
  <%= image_tag course.cover, class: 'img-fluid' if course.cover.attached? %>
  <div class="card-body">
    <%= course.short_description %>
  </div>
  <div class="card-footer text-center">
    <%= enroll_in(course) %>
    <div class="row"></div>
    <%= review(course) %>
    <div class="row"></div>
    <%= certificate(course) %>
  </div>
  <div class="card-footer d-flex">
    <div class="flex-grow-1">
      <i class="text-warning fa-solid fa-star"></i>
      <b>
        <%= course.average_rating %>
      </b>
      (
      <i class="fa-solid fa-user-graduate"></i>
      <%= course.enrollments_count %>
      )
      <i class="fa-solid fa-list-check"></i>
      <%= pluralize(course.lessons_count, 'lesson') %>
    </div>
    <div>
      <i class="fa-solid fa-chalkboard-user"></i>
      <%= link_to course.user.username, user_path(course.user) %>
    </div>
  </div>
  <% if current_user %>
    <% if policy(course).owner? %>
      <div class="card-footer">
        <%= link_to 'Add lesson', new_course_lesson_path(course, @lesson), class: 'btn btn-primary btn-sm text-light' %>
        <%= link_to 'Wizard', course_course_wizard_index_path(course), class: 'btn btn-sm btn-warning text-dark' %>
        <%= link_to 'Destroy', course, class: 'btn btn-sm btn-danger text-light', method: :delete, data: { confirm: 'Are you sure?' } if policy(course).destroy? %>
        <%= link_to analytics_course_path(course), class: 'btn btn-sm btn-info text-light' do %>
          <div class="fa-solid fa-chart-area"></div>
          Analytics
        <% end %>
      </div>
    <% end %>
    <% if policy(current_user).admin? || policy(course).owner? %>
      <div class="card-footer">
        <% if course.published %>
          <span class="badge bg-success">Published</span>
        <% else %>
          <span class="badge bg-danger">Not published</span>
        <% end %>
        <% if course.approved %>
          <span class="badge bg-success">Approved</span>
        <% else %>
          <span class="badge bg-danger">Not approved</span>
        <% end %>
      </div>
      <% if policy(course).approve? %>
        <div class="card-footer">
          <% if course.approved %>
            <%= link_to 'Reject', reject_course_path(course), method: :patch, class: 'btn btn-sm btn-danger' %>
          <% else %>
            <%= link_to 'Approve', approve_course_path(course), method: :patch, class: 'btn btn-sm btn-success' %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <div class="card-footer">
    <% course.tags.each do |tag| %>
      <span class="badge bg-info"><%= tag.name %></span>
    <% end %>
  </div>
</div>

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="d-grid gap-2">
    <div class="form-inputs">
      <%= f.input :title %>
    </div>
    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </div>
<% end %>

app/views/courses/analytics.html.erb
<% content_for :title do %>
  <%= @course.title %>
<% end %>
<div class="d-flex gap-2 mb-3">
  <%= link_to 'Courses', courses_path %> /
  <%= link_to course_path(@course) do %>
    <i class="fa-solid fa-graduation-cap"></i>
    <%= @course.title %>
  <% end %> /
  <%= link_to analytics_course_path(@course) do %>
    <div class="fa-solid fa-chart-area"></div>
    Analytics
  <% end %>
</div>
<h4 class="text-center">
  <%= "Analytics for #{@course.title}" %>
</h4>
Enrollments per day (count)
<%= line_chart @course.enrollments.group_by_day(:created_at).count %>
Enrollments per day (revenue)
<%= line_chart @course.enrollments.group_by_day(:created_at).sum(:price) %>
Unique user views
<%= bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').count %>
Impressions per lesson
<%= bar_chart @course.user_lessons.joins(:lesson).group(:'lessons.title').sum(:impressions) %>

app/views/courses/index.html.erb
<% content_for :title do %>
  <%= action_name.humanize %>
  courses
<% end %>
<h3>
  <div class="text-center">
    <%= action_name.humanize %>
    courses
    <span class="badge bg-info">
      <%= @courses.count %>
    </span>
  </div>
</h3>
<p></p>
<div class="row">
  <div class="col-md-2">
    <%= search_form_for @ransack_courses, as: :courses_search, url: @ransack_path do |f| %>
      <i class="fa-solid fa-filter"></i>
      <b>Filtering</b>
      <%= f.search_field :title_cont, placeholder: "Title", class: "form-control form-control-sm mt-1" %>
      <%= f.search_field :tags_name_cont_any, placeholder: "Tag name", class: "form-control form-control-sm mt-1" %>
      <%= f.search_field :short_description_cont, placeholder: "Description", class: "form-control form-control-sm mt-1" %>
      <%= f.select :language_cont, Course.languages, {prompt: 'Language'}, {class: 'form-select form-select-sm mt-1', data: {}} %>
      <%= f.select :level_cont, Course.levels, {prompt: 'Level'}, {class: 'form-select form-select-sm mt-1', data: {}} %>
      <%= f.search_field :price_eq, placeholder: "Price", class: "form-control form-control-sm mt-1" %>
      <%= f.search_field :user_email_cont, placeholder: "Instructor", class: "form-control form-control-sm mt-1" %>
      <div class="btn-toolbar mt-3" role="toolbar">
        <div class="btn-group me-2">
          <%= f.button type: :submit, class: "btn btn-primary btn-sm" do %>
            <i class="fa-solid fa-magnifying-glass"></i>
            Search
          <% end %>
        </div>
        <div class="btn-group">
          <%= link_to @ransack_path, class: "btn btn-secondary text-light btn-sm" do %>
            <i class="fa-solid fa-filter-circle-xmark"></i>
          <% end %>
        </div>
      </div>
    <% end %>
    <hr>
    <div>
      <i class="fa-solid fa-tags"></i>
      <b>Tags</b>
    </div>
    <% @tags.most_popular.each do |tag| %>
      <%= link_to url_for(controller: controller_name, action: action_name, courses_search: {course_tags_tag_id_eq: tag.id}), class: "btn btn-info text-light tag-btn" do %>
        <%= tag.name %>
        <%= tag.course_tags_count %>
      <% end %>
    <% end %>
    <hr>
    <div>
      <i class="fa-solid fa-sort"></i>
      <b>Sorting</b>
    </div>
    <div class="row">
      <%= sort_link @ransack_courses, :price %>
    </div>
    <div class="row">
      <%= sort_link @ransack_courses, :average_rating, 'Top rated' %>
    </div>
    <div class="row">
      <%= sort_link @ransack_courses, :enrollments_count, 'Most popular' %>
    </div>
    <div class="row">
      <%= sort_link @ransack_courses, :created_at, 'Latest' %>
    </div>
  </div>
  <div class="col-md-10">
    <div class="container my-4">
      <div class="row" data-masonry='{"percentPosition": true }'>
        <% @courses.each do |course| %>
          <div class="col-sm-6 col-lg-4 mb-4">
            <%= render partial: "course", locals: { course: course } %>
          </div>
        <% end %>
      </div>
    </div>
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
</div>

app/views/courses/new.html.erb
<% content_for :title do %>
  New Course
<% end %>
<div class="d-flex gap-2 mb-3">
  <%= link_to 'Courses', courses_path %> /
  New Course
</div>
<div class="card">
  <div class="card-header">
    <h3>
      <i class="fa-solid fa-graduation-cap"></i>
      New Course
    </h3>
  </div>
  <div class="card-body">
    <%= render 'form', course: @course %>
  </div>
  <div class="card-footer">
    <%= link_to 'Back', courses_path %>
  </div>
</div>

app/views/courses/show.html.erb
<% content_for :title do %>
  <%= @course.title %>
<% end %>
<div class="d-flex gap-2 mb-3">
  <%= link_to 'Courses', courses_path %> /
  <%= link_to course_path(@course) do %>
    <i class="fa-solid fa-graduation-cap"></i>
    <%= @course.title %>
  <% end %>
</div>
<div class="row">
  <div class="col-lg-8 order-1 order-lg-1">
    <div class="d-grid gap-2">
      <div class="container-fluid text-lg-left p-4 bg-light">
        <h3 class="mb-4">
          <i class="fa-solid fa-graduation-cap"></i>
          <%= link_to @course.title, @course %>
        </h3>
        <div class="mt-4 mx-auto">
          <i class="fa-solid fa-clock"></i>
          <%= @course.updated_at.strftime('%b-%Y') %>
        </div>
        <div class="mx-auto">
          <i class="fa-solid fa-earth-africa"></i>
          <%= @course.language %>
        </div>
        <div class="mx-auto">
          <i class="fa-solid fa-signal"></i>
          <%= @course.level %>
        </div>
        <div class="mt-3 mx-auto">
          <%= @course.description %>
        </div>
      </div>
      <h5 class="mt-3">
        <i class="fa-solid fa-list-check"></i>
        <%= pluralize(@course.lessons_count, 'Lesson') %>
        <% if current_user && !@course.owned_by?(current_user) %>
          <div class="float-end">
            <i class="fa-solid fa-spinner"></i>
            <%= number_to_percentage(@course.progress(current_user), precision: 0) %>
          </div>
        <% end %>
      </h5>
      <ul class="list-group <%= 'jquery-ui-sortable' if policy(@course).edit? %>">
        <% @lessons.each do |lesson| %>
          <%= content_tag 'div', id: "lesson-#{lesson.id}", data: { model_name: lesson.class.name.underscore, update_url: course_lesson_sort_path(@course, lesson) } do %>
            <li class="list-group-item">
              <%= render partial: 'lessons/lesson_preview', locals: { lesson: lesson } %>
            </li>
          <% end %>
        <% end %>
      </ul>
      <h5 class="mt-3">
        <i class="fa-solid fa-comments"></i>
        <%= pluralize(@recent_reviews.count, 'Review') %>
      </h5>
      <% @recent_reviews.each do |enrollment| %>
        <%= render "enrollments/enrollment", enrollment: enrollment %>
      <% end %>
    </div>
    <div class="row mt-4">
      <h5>
        <i class="fa-solid fa-rocket"></i>
        Similar courses
      </h5>
      <div class="row row-cols-1 row-cols-md-3 g4">
        <% @similar_courses.each do |course| %>
          <% if @course.tags.pluck(:id).intersection(course.tags.pluck(:id)).count.positive? %>
            <div class="col">
              <%= render partial: 'course', locals: { course: course } %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-lg-4 order-0 order-lg-1 mb-3">
    <div class="sticky-top">
      <%= render partial: 'course', locals: { course: @course } %>
    </div>
  </div>
</div>